Big changes: full droidspaces support

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -9,9 +9,16 @@ on:
         type: choice
         default: oneplus
         options:
+          - Manual-Type
           - oneplus
           - xiaomi
           - sony
+
+      brand_manual:
+        description: "Brand-Manual: If selected Manual-Type in previous options, manually type ur brand"
+        required: false
+        type: string
+        default: ""
 
       soc:
         description: "SOC: Type your soc"
@@ -133,8 +140,12 @@ on:
         default: None
         options:
           - None
-          - 5.4-6.6
-          - 3.18-4.19
+          - 6.12
+          - 5.15-6.6
+          - 5.4-5.10
+          - 4.14-4.19
+          - 4.4-4.9
+          - 3.18
 
       has_modules_repo:
         description: "Has-Modules-Repo: Enable this ur kernel has modules repo"
@@ -214,62 +225,53 @@ jobs:
           
       - name: Save options
         run: |
-          echo "brand:${{ inputs.brand }}"
-          echo "soc:${{ inputs.soc }}"
-          echo "clang_version:${{ inputs.clang_version }}"
-          echo "kernel_source:${{ inputs.kernel_source }}"
-          echo "kernel_source_manual:${{ inputs.kernel_source_manual }}"
-          echo "kernel_source_format:${{ inputs.kernel_source_format }}"
-          echo "ksu_type:${{ inputs.ksu_type }}"
-          echo "susfs-gki:${{ inputs.susfs-gki }}"
-          echo "susfs-nongki:${{ inputs.susfs-nongki }}"
-          echo "droidspaces:${{ inputs.droidspaces }}"
-          echo "has_modules_repo:${{ inputs.has_modules_repo }}"
-          echo "enable_tmpfs-xattr:${{ inputs.enable_tmpfs-xattr }}"
-          echo "enable_gcc:${{ inputs.enable_gcc }}"
-          echo "enable_gcc_32bits:${{ inputs.enable_gcc_32bits }}"
-          echo "fuck_modules_sig_protect:${{ inputs.fuck_modules_sig_protect }}"
-          echo "fuck_werror:${{ inputs.fuck_werror }}"
-          echo "enable_my_own_susfs_patch:${{ inputs.enable_my_own_susfs_patch }}"
-
-          echo "brand:${{ inputs.brand }}" >> options.txt
-          echo "soc:${{ inputs.soc }}" >> options.txt
-          echo "clang_version:${{ inputs.clang_version }}" >> options.txt
-          echo "kernel_source:${{ inputs.kernel_source }}" >> options.txt
-          echo "kernel_source_manual:${{ inputs.kernel_source_manual }}" >> options.txt
-          echo "kernel_source_format:${{ inputs.kernel_source_format }}" >> options.txt
-          echo "ksu_type:${{ inputs.ksu_type }}" >> options.txt
-          echo "susfs-gki:${{ inputs.susfs-gki }}" >> options.txt
-          echo "susfs-nongki:${{ inputs.susfs-nongki }}" >> options.txt
-          echo "droidspaces:${{ inputs.droidspaces }}" >> options.txt
-          echo "has_modules_repo:${{ inputs.has_modules_repo }}" >> options.txt
-          echo "enable_tmpfs-xattr:${{ inputs.enable_tmpfs-xattr }}" >> options.txt
-          echo "enable_gcc:${{ inputs.enable_gcc }}" >> options.txt
-          echo "enable_gcc_32bits:${{ inputs.enable_gcc_32bits }}" >> options.txt
-          echo "fuck_modules_sig_protect:${{ inputs.fuck_modules_sig_protect }}" >> options.txt
-          echo "fuck_werror:${{ inputs.fuck_werror }}" >> options.txt
-          echo "enable_my_own_susfs_patch:${{ inputs.enable_my_own_susfs_patch }}" >> options.txt
+          {
+            echo "brand:${{ inputs.brand }}"
+            echo "brand_manual:${{inputs.brand_manual}}"
+            echo "soc:${{ inputs.soc }}"
+            echo "clang_version:${{ inputs.clang_version }}"
+            echo "kernel_source:${{ inputs.kernel_source }}"
+            echo "kernel_source_manual:${{ inputs.kernel_source_manual }}"
+            echo "kernel_source_format:${{ inputs.kernel_source_format }}"
+            echo "ksu_type:${{ inputs.ksu_type }}"
+            echo "susfs-gki:${{ inputs.susfs-gki }}"
+            echo "susfs-nongki:${{ inputs.susfs-nongki }}"
+            echo "droidspaces:${{ inputs.droidspaces }}"
+            echo "has_modules_repo:${{ inputs.has_modules_repo }}"
+            echo "enable_tmpfs-xattr:${{ inputs.enable_tmpfs-xattr }}"
+            echo "enable_gcc:${{ inputs.enable_gcc }}"
+            echo "enable_gcc_32bits:${{ inputs.enable_gcc_32bits }}"
+            echo "fuck_modules_sig_protect:${{ inputs.fuck_modules_sig_protect }}"
+            echo "fuck_werror:${{ inputs.fuck_werror }}"
+            echo "enable_my_own_susfs_patch:${{ inputs.enable_my_own_susfs_patch }}"
+          } | tee -a options.txt
       - name: Clone Kernel Source
         run: |
-          if [[ "${{ inputs.kernel_source }}" == "Manual-Type" ]]; then
+          if [[ "${{ inputs.brand }}" == "Manual-Type" ]]; then
 
-            git clone --depth=1 -b ${{ inputs.kernel_branch }} https://github.com/${{ inputs.kernel_source_manual }}/${{ inputs.kernel_source_format }}_${{ inputs.brand }}_${{ inputs.soc }}.git ${{ inputs.soc }} || exit 1
-
-            if [[ "${{ inputs.has_modules_repo }}" == "true" ]]; then
-
-              git clone --depth=1 -b ${{ inputs.kernel_branch }} https://github.com/${{ inputs.kernel_source_manual }}/${{ inputs.kernel_source_format }}_${{ inputs.brand }}_${{ inputs.soc }}-modules.git ${{ inputs.soc }}-modules || exit 1
-
-            fi
+            brand="${{ inputs.brand_manual }}"
 
           else
 
-            git clone --depth=1 -b ${{ inputs.kernel_branch }} https://github.com/${{ inputs.kernel_source }}/${{ inputs.kernel_source_format }}_${{ inputs.brand }}_${{ inputs.soc }}.git ${{ inputs.soc }} || exit 1
+            brand="${{ inputs.brand }}"
 
-            if [[ "${{ inputs.has_modules_repo }}" == "true" ]]; then
+          fi
 
-                git clone --depth=1 -b ${{ inputs.kernel_branch }} https://github.com/${{ inputs.kernel_source }}/${{ inputs.kernel_source_format }}_${{ inputs.brand }}_${{ inputs.soc }}-modules.git ${{ inputs.soc }}-modules || exit 1
+          if [[ "${{ inputs.kernel_source }}" == "Manual-Type" ]]; then
 
-            fi
+            source="${{ inputs.kernel_source_manual }}"
+
+          else
+
+            source="${{ inputs.kernel_source }}"
+
+          fi
+
+          git clone --depth=1 -b ${{ inputs.kernel_branch }} https://github.com/${ source }/${{ inputs.kernel_source_format }}_${ brand }_${{ inputs.soc }}.git ${{ inputs.soc }} || exit 1
+
+          if [[ "${{ inputs.has_modules_repo }}" == "true" ]]; then
+
+            git clone --depth=1 -b ${{ inputs.kernel_branch }} https://github.com/${ source }/${{ inputs.kernel_source_format }}_${ brand }_${{ inputs.soc }}-modules.git ${{ inputs.soc }}-modules || exit 1
 
           fi
 
@@ -278,43 +280,38 @@ jobs:
           case "${{ inputs.clang_version }}" in
 
             "clang-r416183b1")
-              curl -LO https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android12-qpr3-release/clang-r416183b1.tar.gz
-              ;;
+            curl -LO https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android12-qpr3-release/clang-r416183b1.tar.gz || exit 1
+            ;;
 
             "clang-r450784d")
-              curl -LO https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android13-qpr3-release/clang-r450784d.tar.gz
-              ;;
+            curl -LO https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android13-qpr3-release/clang-r450784d.tar.gz || exit 1
+            ;;
 
             "clang-r487747c")
-              curl -LO https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android14-qpr3-release/clang-r487747c.tar.gz
-              ;;
+            curl -LO https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android14-qpr3-release/clang-r487747c.tar.gz || exit 1
+            ;;
 
             "clang-r536225")
-              curl -LO https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android15-qpr2-release/clang-r536225.tar.gz
-              ;;
+            curl -LO https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android15-qpr2-release/clang-r536225.tar.gz || exit 1
+            ;;
 
             "clang-r547379")
-              curl -LO https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android16-qpr2-release/clang-r547379.tar.gz
-              ;;
-              
+            curl -LO https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android16-qpr2-release/clang-r547379.tar.gz || exit 1
+            ;;
+
             "clang-r563880c")
-              curl -LO https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android16-qpr2-release/clang-r563880c.tar.gz
-              ;;
-              
+            curl -LO https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/android16-qpr2-release/clang-r563880c.tar.gz || exit 1
+            ;;
+
           esac
 
           mkdir -p toolchains/${{ inputs.clang_version }}
-          
           tar -xf "${{ inputs.clang_version }}.tar.gz" -C "toolchains/${{ inputs.clang_version }}" || exit 1
-
           if [[ "${{ inputs.enable_gcc_32bits }}" == "true" ]]; then
-
             curl -LO https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/+archive/refs/heads/android12L-release.tar.gz
             mkdir -p toolchains/arm-linux-androideabi
             tar -xf android12L-release.tar.gz -C toolchains/arm-linux-androideabi
-         
           fi
-
 
       - name: Include goodies
         run: |
@@ -346,25 +343,62 @@ jobs:
               ;;
 
             "ReSukiSU"|"ReSukiSU-with-susfs")
-              curl -LSs "https://raw.githubusercontent.com/ReSukiSU/ReSukiSU/main/kernel/setup.sh" | bash -s main
+              curl -LSs "https://raw.githubusercontent.com/ReSukiSU/ReSukiSU/main/kernel/setup.sh" | bash -s main || exit 1
               ;;
 
           esac
 
-          if [[ "${{ inputs.droidspaces }}" == "5.4-6.6" ]]; then
 
-            curl -Lo droidspaces.patch https://raw.githubusercontent.com/ravindu644/Droidspaces-OSS/refs/heads/main/Documentation/resources/kernel-patches/GKI/below-kernel-6.12/001.GKI-below-6.12-fix_sysvipc_kabi_6_7_8.patch
-            patch -p1 < droidspaces.patch
+          if [[ "${{ inputs.droidspaces }}" == "6.12" ]]; then
+
+            curl -Lo patch-for-6.12.patch https://raw.githubusercontent.com/ravindu644/Droidspaces-OSS/refs/heads/main/Documentation/resources/kernel-patches/GKI/kernel-6.12/001.GKI-6.12-or-above-fix_sysvipc_kabi.patch || exit 1
+            patch -p1 < patch-for-6.12.patch
 
             cp ${GITHUB_WORKSPACE}/configs/droidspaces-gki.config arch/arm64/configs/vendor/droidspaces.config
 
-          elif [[ "${{ inputs.droidspaces }}" == "3.18-4.19" ]]; then
+          elif [[ "${{ inputs.droidspaces }}" == "5.15-6.6" ]]; then
 
-            # Why there is no 01.fix_kernel_panic_in_xt_qtaguid.patch? Because I cant find net/netfilter/xt_qtaguid.c in my k4.14 4.19 5.4
-            # 为什么没有01.fix_kernel_panic_in_xt_qtaguid.patch? 在我用的4.14 4.19 5.4内无此文件
+            curl -Lo patch-for-below-6.12.patch https://raw.githubusercontent.com/ravindu644/Droidspaces-OSS/refs/heads/main/Documentation/resources/kernel-patches/GKI/below-kernel-6.12/001.GKI-below-6.12-fix_sysvipc_kabi_6_7_8.patch || exit 1
+            patch -p1 < patch-for-below-6.12.patch
 
-            curl -Lo patch2.patch https://raw.githubusercontent.com/ravindu644/Droidspaces-OSS/refs/heads/main/Documentation/resources/kernel-patches/non-GKI/02.fix_restore%20cgroup%20file%20prefix%20handling%20.patch || exit 1
-            patch -p1 < patch2.patch
+            cp ${GITHUB_WORKSPACE}/configs/droidspaces-gki.config arch/arm64/configs/vendor/droidspaces.config
+
+          elif [[ "${{ inputs.droidspaces }}" == "5.10" ]]; then
+
+            curl -Lo patch-for-below-6.12.patch https://raw.githubusercontent.com/ravindu644/Droidspaces-OSS/refs/heads/main/Documentation/resources/kernel-patches/GKI/below-kernel-6.12/001.GKI-below-6.12-fix_sysvipc_kabi_6_7_8.patch || exit 1
+            patch -p1 < patch-for-below-6.12.patch || exit 1
+
+            curl -Lo patch-for-5.10-or-lower.patch https://raw.githubusercontent.com/ravindu644/Droidspaces-OSS/refs/heads/main/Documentation/resources/kernel-patches/GKI/below-kernel-6.12/002.5.10_or_lower_use_android_abi_padding_for_posix_mqueue.patch || exit 1
+            patch -p1 < patch-for-5.10-or-lower.patch
+
+            cp ${GITHUB_WORKSPACE}/configs/droidspaces-gki.config arch/arm64/configs/vendor/droidspaces.config
+
+          elif [[ "${{ inputs.droidspaces }}" == "5.4" ]]; then
+
+            curl -Lo patch-for-below-6.12.patch https://raw.githubusercontent.com/ravindu644/Droidspaces-OSS/refs/heads/main/Documentation/resources/kernel-patches/GKI/below-kernel-6.12/001.GKI-below-6.12-fix_sysvipc_kabi_6_7_8.patch || exit 1
+            patch -p1 < patch-for-below-6.12.patch
+
+            curl -Lo patch-for-5.10-or-lower.patch https://raw.githubusercontent.com/ravindu644/Droidspaces-OSS/refs/heads/main/Documentation/resources/kernel-patches/GKI/below-kernel-6.12/002.5.10_or_lower_use_android_abi_padding_for_posix_mqueue.patch || exit 1
+            sed -i '/ANDROID_OEM_DATA_ARRAY/d' patch-for-5.10-or-lower.patch
+            patch -p1 < patch-for-5.10-or-lower.patch
+
+            cp ${GITHUB_WORKSPACE}/configs/droidspaces-gki.config arch/arm64/configs/vendor/droidspaces.config
+
+          elif [[ "${{ inputs.droidspaces }}" == "4.14-4.19" ]]; then
+
+            curl -Lo patch-fix-cgroup.patch https://raw.githubusercontent.com/ravindu644/Droidspaces-OSS/refs/heads/main/Documentation/resources/kernel-patches/non-GKI/02.fix_restore%20cgroup%20file%20prefix%20handling%20.patch || exit 1
+            patch -p1 < patch-fix-cgroup.patch
+
+            cp ${GITHUB_WORKSPACE}/configs/droidspaces-nongki.config arch/arm64/configs/vendor/droidspaces.config
+
+          elif [[ "${{ inputs.droidspaces }}" == "4.4-4.9" ]]; then
+
+            cp ${GITHUB_WORKSPACE}/configs/droidspaces-nongki.config arch/arm64/configs/vendor/droidspaces.config
+
+          elif [[ "${{ inputs.droidspaces }}" == "3.18" ]]; then
+
+            curl -Lo patch-fix-xt_qtaguid.patch https://raw.githubusercontent.com/ravindu644/Droidspaces-OSS/refs/heads/main/Documentation/resources/kernel-patches/non-GKI/01.fix_kernel_panic_in_xt_qtaguid.patch || exit 1
+            patch -p1 < patch-fix-xt_qtaguid.patch
 
             cp ${GITHUB_WORKSPACE}/configs/droidspaces-nongki.config arch/arm64/configs/vendor/droidspaces.config
 
@@ -400,13 +434,12 @@ jobs:
 
               fi
 
-              patch -p1 < susfs.patch || true
+              patch -p1 < susfs.patch
 
             elif [[ "${{ inputs.susfs-nongki }}" != "None" ]]; then
 
               curl -Lo susfs.patch https://raw.githubusercontent.com/JackA1ltman/NonGKI_Kernel_Build_2nd/refs/heads/mainline/Patches/Patch/susfs_patch_to_${{ inputs.susfs-nongki }}.patch || exit 1
               curl -Lo inline.sh https://raw.githubusercontent.com/JackA1ltman/NonGKI_Kernel_Build_2nd/refs/heads/mainline/Patches/susfs_inline_hook_patches.sh || exit 1
-
               patch -p1 < susfs.patch
               bash inline.sh
 
@@ -424,7 +457,6 @@ jobs:
           export SUBARCH=arm64
           export LLVM=1
           export LLVM_IAS=1
-
           if [[ "${{ inputs.enable_gcc }}" == "true" ]]; then
 
             export CROSS_COMPILE=aarch64-linux-gnu-
@@ -432,17 +464,20 @@ jobs:
           fi
 
           if [[ "${{ inputs.enable_gcc_32bits }}" == "true" ]]; then
-            
+
             export CROSS_COMPILE_ARM32=${GITHUB_WORKSPACE}/toolchains/arm-linux-androideabi/bin/arm-linux-androideabi-
-          
-          fi
-          
-          if [[ "${{ inputs.droidspaces }}" != "None" ]]; then
-            export DROIDSPACES_CONFIG="vendor/droidspaces.config"
-          else
-            export DROIDSPACES_CONFIG=""
+
           fi
 
+          if [[ "${{ inputs.droidspaces }}" != "None" ]]; then
+
+            export DROIDSPACES_CONFIG="vendor/droidspaces.config"
+
+          else
+
+            export DROIDSPACES_CONFIG=""
+
+          fi
 
           cd ${{ inputs.soc }} || exit 1
 
@@ -461,28 +496,22 @@ jobs:
 
             case "${{ inputs.kernel_configs }}" in
 
-              "oplus-sm8150-los")
-              make O=out vendor/sm8150-perf_defconfig vendor/oplus.config $DROIDSPACES_CONFIG
+              "oplus-sm8150-los")make O=out vendor/sm8150-perf_defconfig vendor/oplus.config $DROIDSPACES_CONFIG
               ;;
 
-              "oplus-sm8150-yaap")
-              make O=out gulch_defconfig vendor/debugfs.config $DROIDSPACES_CONFIG
+              "oplus-sm8150-yaap")make O=out gulch_defconfig vendor/debugfs.config $DROIDSPACES_CONFIG
               ;;
 
-              "oplus-sm8250-los")
-              make O=out vendor/kona-perf_defconfig vendor/oplus.config $DROIDSPACES_CONFIG
+              "oplus-sm8250-los")make O=out vendor/kona-perf_defconfig vendor/oplus.config $DROIDSPACES_CONFIG
               ;;
 
-              "oplus-sm8350-los")
-              make O=out vendor/lahaina-qgki_defconfig $DROIDSPACES_CONFIG
+              "oplus-sm8350-los")make O=out vendor/lahaina-qgki_defconfig $DROIDSPACES_CONFIG
               ;;
 
-              "oplus-sm8550-los")
-              make O=out gki_defconfig vendor/kalama_GKI.config vendor/oplus/kalama_GKI.config vendor/debugfs.config $DROIDSPACES_CONFIG
+              "oplus-sm8550-los")make O=out gki_defconfig vendor/kalama_GKI.config vendor/oplus/kalama_GKI.config vendor/debugfs.config $DROIDSPACES_CONFIG
               ;;
 
-              "oplus-sm8650-los")
-              make O=out gki_defconfig vendor/pineapple_GKI.config vendor/oplus/pineapple_GKI.config $DROIDSPACES_CONFIG
+              "oplus-sm8650-los")make O=out gki_defconfig vendor/pineapple_GKI.config vendor/oplus/pineapple_GKI.config $DROIDSPACES_CONFIG
               ;;
 
             esac
@@ -545,30 +574,27 @@ jobs:
           if [[ "${{ inputs.enable_gcc }}" == "true" ]]; then
 
             export CROSS_COMPILE=aarch64-linux-gnu-
-            
+
           fi
 
           if [[ "${{ inputs.enable_gcc_32bits }}" == "true" ]]; then
-            
+
             export CROSS_COMPILE_ARM32=${GITHUB_WORKSPACE}/toolchains/arm-linux-androideabi/bin/arm-linux-androideabi-
-          
+
           fi
 
           cd ${{ inputs.soc }} || exit 1
-
+          set -o pipefail
           make -j$(nproc) O=out Image 2>&1 | tee ${GITHUB_WORKSPACE}/build.log
 
       - name: Make AnyKernel3
         run: |
           ZIP_NAME="${{ inputs.soc }}_${{ inputs.kernel_source }}-${{ inputs.kernel_branch }}_${{ inputs.ksu_type }}_$(date -u +"%Y%m%d_%H%M")"
           git clone https://github.com/Kernel-SU/AnyKernel3.git || exit 1
-
           cp ${{ inputs.soc }}/out/arch/arm64/boot/Image AnyKernel3/Image
           cp ${{ inputs.soc }}/out/arch/arm64/boot/Image ./Image
           cd AnyKernel3 || exit 1
-
           sed -i "s|ksu_supported=false|ksu_supported=true|" anykernel.sh
-
           zip -r9 ../"${ZIP_NAME}.zip" * -x .git
 
       - name: Create GitHub Release
